image: mcr.microsoft.com/playwright:v1.41.2-jammy

stages:
  - test
  - report
  - save
  - deploy

variables:
  ALLURE_VERSION: "2.24.0"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

cache:
  key: pages-cache
  paths:
    - node_modules/
    - public/

before_script:
  - npm ci

playwright_tests:
  stage: test
  script:
    - npx playwright test || true
  artifacts:
    when: always
    paths:
      - allure-results/
    expire_in: 30 days

generate_allure_report:
  stage: report
  image: eclipse-temurin:17-jdk
  before_script: []
  dependencies:
    - playwright_tests
  script:
    - apt-get update && apt-get install -y wget unzip
    - wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip
    - unzip allure-${ALLURE_VERSION}.zip
    - ./allure-${ALLURE_VERSION}/bin/allure generate allure-results --clean -o allure-report
  artifacts:
    when: always
    paths:
      - allure-report/
    expire_in: 7 days

save_mongo:
  image: node:18
  stage: save
  dependencies:
    - playwright_tests
  script:
    - npm install mongodb
    - node saveToMongo.js
  only:
    - main
pages:
  stage: deploy
  dependencies:
    - generate_allure_report
  script:
    - mkdir -p public/$CI_PIPELINE_ID
    - cp -r allure-report/* public/$CI_PIPELINE_ID/

    - |
      cat << 'EOF' > public/index.html
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Relatórios Allure</title>
      </head>
      <body>
        <h1>📊 Histórico de Relatórios Allure</h1>
        <div>
      EOF

    - |
      formatted_date=$(date -d "$CI_PIPELINE_CREATED_AT" +"%d/%m/%Y")

      for dir in $(ls -d public/*/ 2>/dev/null | sort -rn); do
        name=$(basename "$dir")

        echo "<div>
        <a href='./$name/'>#${CI_PIPELINE_IID} • ${CI_COMMIT_BRANCH}</a>
        <div>Commit: ${CI_COMMIT_SHORT_SHA}</div>
        <div>Data: ${formatted_date}</div>
        </div><hr>" >> public/index.html
      done

    - |
      cat << 'EOF' >> public/index.html
        </div>
      </body>
      </html>
      EOF

  artifacts:
    paths:
      - public
  when: always
  only:
    - main